spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/employees
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/db_changelog-master.yml
  servlet:
    context-path: /api
springdoc:
  api-docs:
    path: /v3/api-docs  # Путь для API-документации
  swagger-ui:
    path: /swagger-ui.html  # Путь для Swagger UI
    operationsSorter: alpha  # Сортировка операций по алфавиту