spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/employees
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelogs/db.changelog-master.yml
  servlet:
    context-path: /api
